In [29]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [30]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


In [31]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    # data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [32]:
training_set


<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [33]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 87.    79.    94.  ]
   [ 97.5   89.5  104.5 ]
   [ 91.    83.    98.  ]
   ...
   [134.25 122.25 144.25]
   [128.75 116.75 138.75]
   [132.25 120.25 142.25]]

  [[ 91.25  83.25  98.25]
   [113.5  105.5  120.5 ]
   [ 94.25  86.25 101.25]
   ...
   [125.   113.   135.  ]
   [128.25 116.25 138.25]
   [126.75 114.75 136.75]]

  [[ 90.    82.    97.  ]
   [102.    94.   109.  ]
   [ 88.75  80.75  95.75]
   ...
   [130.75 118.75 140.75]
   [132.   120.   142.  ]
   [134.25 122.25 144.25]]

  ...

  [[100.25  93.25 109.25]
   [105.75  98.75 114.75]
   [ 90.25  83.25  99.25]
   ...
   [123.5  115.5  138.5 ]
   [122.25 114.25 137.25]
   [122.75 114.75 137.75]]

  [[ 97.75  90.75 106.75]
   [ 92.5   85.5  101.5 ]
   [ 97.    90.   106.  ]
   ...
   [121.75 113.75 136.75]
   [124.5  116.5  139.5 ]
   [123.25 115.25 138.25]]

  [[ 92.5   85.5  101.5 ]
   [ 96.5   89.5  105.5 ]
   [102.    95.   111.  ]
   ...
   [118.   110.   133.  ]
   [123.5  115.5  138.5 ]
   [121.25 113.25 13

In [2]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential


In [3]:
model = Sequential()

In [54]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [55]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [56]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [57]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [58]:
model.add(Flatten())

In [59]:
model.add(Dense(units=1024,activation='relu'))

In [60]:
model.add(Dense(units=38,activation='softmax'))

In [61]:
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [62]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_18 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_19 (Conv2D)                   │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_9 (MaxPooling2D)       │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_20 (Conv2D)                   │ (None, 64, 64, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_21 (Conv2D)                   │ (None, 64, 64, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_10 (MaxPooling2D)      │ (None, 32, 32, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_22 (Conv2D)                   │ (None, 32, 32, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_23 (Conv2D)                   │ (None, 32, 32, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_11 (MaxPooling2D)      │ (None, 16, 16, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_24 (Conv2D)                   │ (None, 16, 16, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_25 (Conv2D)                   │ (None, 16, 16, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 8, 8, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ (None, 16384)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1024)                │      16,778,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 38)                  │          38,950 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 17,989,446 (68.62 MB)

 Trainable params: 17,989,446 (68.62 MB)

 Non-trainable params: 0 (0.00 B)

In [63]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1544s 701ms/step - accuracy: 0.4656 - loss: 2.0637 - val_accuracy: 0.8526 - val_loss: 0.4639
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1499s 682ms/step - accuracy: 0.8698 - loss: 0.4020 - val_accuracy: 0.8070 - val_loss: 0.6350
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1559s 710ms/step - accuracy: 0.9177 - loss: 0.2518 - val_accuracy: 0.8943 - val_loss: 0.3441
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1623s 739ms/step - accuracy: 0.9392 - loss: 0.1827 - val_accuracy: 0.8969 - val_loss: 0.3409
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1507s 686ms/step - accuracy: 0.9476 - loss: 0.1634 - val_accuracy: 0.8875 - val_loss: 0.4062
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1508s 686ms/step - accuracy: 0.9539 - loss: 0.1419 - val_accuracy: 0.9154 - val_loss: 0.3127
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1505s 685ms/step - accuracy: 0.9593 - loss: 0.1240 - val_accuracy: 0.9169 - val_loss: 0.3030
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1505s 685ms/s

In [4]:
train_loss,train_acc = model.evaluate(training_set)

NameError: name 'training_set' is not defined

In [ ]:
print(train_loss,train_acc)

In [ ]:
val_loss,val_acc = model.evaluate(validation_set)

In [ ]:
print(val_loss,val_acc)

In [ ]:
model.save("trained_model.keras")